# Generated by Django 4.2.2 on 2023-07-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0002_representante_deportista_representante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deportista',
            old_name='representante',
            new_name='nombre_representante',
        ),
    ]
