# Generated by Django 4.2.2 on 2023-07-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportistas', '0003_rename_representante_deportista_nombre_representante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representante',
            name='nombre_representante',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
